FROM apache/seata-server:2.6.0

COPY ./config/application.yml /seata-server/resources
COPY ./lib/mysql-connector-java-5.1.42.jar /seata-server/libs
COPY ./lib/mysql-connector-java-8.0.27.jar /seata-server/libs