name: "pcmall-docker"
services:
  pcmall-redis:
    image: redis
    container_name: pcmall-redis
    ports:
      - "6379:6379"
    volumes:
      - pcmall-redis-data:/data

  pcmall-nacos:
    image: nacos/nacos-server:v3.1.0
    container_name: pcmall-nacos
    environment:
      - PREFER_HOST_MODE=hostname
      - MODE=standalone
      - NACOS_AUTH_IDENTITY_KEY=serverIdentity
      - NACOS_AUTH_IDENTITY_VALUE=security
      - NACOS_AUTH_TOKEN=VGhpc0lzTXlDdXN0b21TZWNyZXRLZXkwMTIzNDU2Nzg=
    ports:
      - "8080:8080"
      - "8848:8848"
      - "9848:9848"
    volumes:
      - pcmall-nacos-data:/home/nacos

  pcmall-seata:
    container_name: pcmall-seata
    build:
      context: ./seata
    ports:
      - "7091:7091"
      - "8091:8091"
    environment:
      - STORE_MODE=db
      - SEATA_IP=10.9.140.91 #不能是127.0.0.1 可以是宿主机地址
      - SEATA_PORT=8091
    volumes:
      - pcmall-seata-data:/seata-server
      - "/usr/share/zoneinfo/Asia/Shanghai:/etc/localtime"  #设置系统时区
      - "/usr/share/zoneinfo/Asia/Shanghai:/etc/timezone"   #设置时区
    extra_hosts:
      - "host.docker.internal:host-gateway"

  pcmall-seata-naming-server:
    image: apache/seata-naming-server:2.6.0.jdk25
    container_name: pcmall-seata-naming-server
    ports:
      - "8082:8081" #宿主：容器
      - "10055:10055"
    environment:
      - SERVER_PORT=8081
      - SEATA_SECURITY_SECRETKEY=TXlDdXN0b21TZWNyZXRLZXlGb3JTZWF0YUpXVDIwMjQ=
      - SEATA_SECURITY_TOKEN_VALIDITY=1800000

  pcmall-sentinel:
    container_name: pcmall-sentinel
    build:
      context: ./sentinel
    ports:
      - "8088:8088"

  pcmall-rocketmq-nameserver:
    image: apache/rocketmq:5.3.2
    container_name: pcmall-rocketmq-nameserver
    ports:
      - "9876:9876"
    networks:
      - rocketmq
    command: sh mqnamesrv
    volumes:
      - pcmall-rocketmq-data:/home/rocketmq
  pcmall-rocketmq-broker:
    image: apache/rocketmq:5.3.2
    container_name: pcmall-rocketmq-broker
    ports:
      - "10909:10909"
      - "10911:10911"
      - "10912:10912"
    environment:
      - NAMESRV_ADDR=pcmall-rocketmq-nameserver:9876
    depends_on:
      - pcmall-rocketmq-nameserver
    networks:
      - rocketmq
    command: sh mqbroker -c ../conf/broker.conf
    volumes:
      - pcmall-rocketmq-data:/home/rocketmq
  pcmall-rocketmq-proxy:
    image: apache/rocketmq:5.3.2
    container_name: pcmall-rocketmq-proxy
    networks:
      - rocketmq
    depends_on:
      - pcmall-rocketmq-broker
      - pcmall-rocketmq-nameserver
    ports:
      - "8089:8080"
      - "8081:8081"
    restart: on-failure
    environment:
      - NAMESRV_ADDR=pcmall-rocketmq-nameserver:9876
    command: sh mqproxy
    volumes:
      - pcmall-rocketmq-data:/home/rocketmq

networks:
  rocketmq:
    name: rocketmq
    driver: bridge

volumes:
  pcmall-redis-data:
  pcmall-nacos-data:
  pcmall-seata-data:
  pcmall-rocketmq-data:

