server.port=12000
spring.application.name=pcmall-consumer-admin
spring.cloud.nacos.discovery.server-addr=127.0.0.1:8848

spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.password=
spring.data.redis.database=0

logging.level.com.example.pcmallconsumeradmin=debug