server.port=10000
spring.application.name=pcmall-gateway
spring.cloud.nacos.discovery.server-addr=127.0.0.1:8848

#????????
spring.cloud.gateway.discovery.locator.enabled=true

#????id ??????,??????
spring.cloud.gateway.routes[0].id=pcmall-consumer-mobile
#?????uri   lb://nacos??????
spring.cloud.gateway.routes[0].uri=lb://pcmall-consumer-mobile
#??????,????,??servicerId?pcmall-consumer-mobile?/mobile/**??
spring.cloud.gateway.routes[0].predicates= Path=/mobile/**
# ??????????
spring.cloud.gateway.routes[0].filters= StripPrefix=1

spring.cloud.gateway.routes[1].id=pcmall-consumer-admin
spring.cloud.gateway.routes[1].uri=lb://pcmall-consumer-admin
spring.cloud.gateway.routes[1].predicates= Path=/admin/**
spring.cloud.gateway.routes[1].filters= StripPrefix=1